version: '3'
services:
  web:
    command: python docker_quickstart.py
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
    ports:
      - 81:5000
    volumes:
      - ./logs:/code/logs
      - .:/code
