version: '3'
services:
  web:
    command: python docker_quickstart.py
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    volumes:
      - ./logs:/code/logs
